apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "analytics-service.fullname" . }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
automountServiceAccountToken: false