spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/urlshortener?currentSchema=user_service
    username: postgres
    password: postgres

  flyway:
    schemas: user_service
    create-schemas: true

  data:
    redis:
      host: redis
      port: 6379
app:
  security:
    jwt:
      private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDizk0fL7JVr3DJNQ45L274PpERZYQXv0EkB9Yv0OYcGpDfEb/mv9DP4KJPhcf/p2twRyTG6ZM2wO2RzwpYj1Ki+sP7lEUzLnWp5WUj9fVKNojBMkFIM4kEf80UM4OZuNowDQk206OlBy0IxbeGdOnflP5Zq+O9E5ClajFkJSWZlUwrVpeEpwvk/koIf9/YpOcDghECcbg/Ce9OAfalVl8FhNakGELAoQAHMr3EhAhoovNjLwSb6QHx8FitCM2DC1+twdYnLiFZGLpO6K8QxtYCN3I6GTbw/gr4aC7+P9OaElLoSyLFYYLeg77XaG3eZVL7EptitYO1JounkRGYQnNPAgMBAAECggEAJu0hb2jQQsSJpv7kIgxyD0ktvL6fnTPGClkN+cbwt4IXuzFgrkndnNABC4T6fnZNikermDgefBdArvXJ4Mk4daB0YolgFxiyOSaV5UYhg0s4zW/CpJGzwoHswLrWq1t+lyClpDNOstQ4dnj4tqr6ONVpkhpeS+U/viQrtfRqL6GNUQhnE+wkq0d+wJ21t4FPrbdmM78SLK1uVEXRMFiEwamfv8hbAWITXz+o5mNzBFGSTLqQW41WCg8nVECK4dJjAoMbtMIw4l92q62AFVsP1OYHPemmR+7q5h1kNBKHublAeeSh/GpPf/YajZbvsLIfE0OLLr4gaudjUQRgLf11gQKBgQD9HTUmlPFiA3A6l0NSy+aRcTZK/2+qJzxdrFC56KCk85BLB0j/nqn4cqgitPTRYbHi2rTJ6sd/wwsaltD/VgpHJpILnQKxira+bh1bKys0C0XFf32TrxnzVD8NJeSYetNbX/YUB0cxrqdW7U6QKDSE2kMGCm9p+XJrRmEbaGB8MwKBgQDlZE4MJkJlQFJ5lzBjyB9mWDwGk9I3Vs+A134hpkaLOgyMIHLixkPB/ytgS10coZo+0b5kbi3agRN1XFILTL9wLXc0sYvPHE2/50ELur+Q2a2qdE5XejdrSDSM33x27bLmWIMI5GxYPHqSzO9SbmlBFAGB/h2y1hvzZb8L+3+QdQKBgQDz2kbRo98mAZAHMqHOy9iXuM2I1a0b7e8PhCrF4SObp3gVgLBIbPDuBnCL93CBpLB/kRtqCMIpCZzSAgjaZmdCgxtjCuKEb9J9hpLLubxGyLFwg9JVDPZgYoLYRPCGIpcryjjGtPhXGh/n9HqjEcj/UVQPJtCN9Z/RUB3QDPAf1wKBgGWbYWrGQ6Cftih/jIKWMTpfGO986J90h2M1kHwNL7AZ3VbwRJMoaPj0Mt1rZGn7NtxegWvw1cS0ac8RPpIcw6tHqEah4iCyE8pN/6TXamUZ1m/rJoxe6U9O42AG2hW/wf9/80KsE0WePFjsB5HGsD6QQv62dacyaZ0NU2tWUjHFAoGAdRH8XpHq8HthOzP1DBMmonA7C1U6x9nPRXTVwG9YAWr+6ICiEJN1cj3c0l3mqgbjsDXcwixynnO5BQ3kbNpb3JvcLEcadrDJb3hXALxv1B+XJ9fU2XJWRry62cz09/0/W6yjg3RVb2Txx4Wz5WCPnDYWWuwck4zBAg/cWYJKym0=
  dev:
    login:
      email: demo@example.com
      password-hash: $2b$12$gw2dbTtLaNuFEY52En5ZTeacxoeqaYsRdCDRGJsyBWB2k3cGDpg7O
