apiVersion: v1
kind: Namespace
metadata:
  name: url-shortener
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/managed-by: argocd