apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
type: Opaque
stringData:
  db-password: <base64-master-password-from-secretsmanager>
  aws-access-key-id: <from-iam-user-or-irsa-disabled>
  aws-secret-access-key: <from-iam-user-or-irsa-disabled>
  jwt-public-key: <rsa-public-key-pem>