name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "url-shortener-ui/**"
  pull_request:
    branches: [main]
    paths:
      - "url-shortener-ui/**"

jobs:
  build:
    name: Lint, test & build Angular MFEs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mfe: [shared-lib, auth-remote, links-remote, analytics-remote, shell]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: url-shortener-ui/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: url-shortener-ui

      - name: Build shared-lib
        run: npx ng build shared-lib --configuration=production
        if: matrix.mfe != 'shared-lib'
        working-directory: url-shortener-ui

      - name: Build ${{ matrix.mfe }}
        run: npx ng build ${{ matrix.mfe }} --configuration=production
        working-directory: url-shortener-ui

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.mfe }}
          path: url-shortener-ui/dist/${{ matrix.mfe }}
          retention-days: 7

  publish:
    name: Build & push MFE images
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        mfe: [shell, auth-remote, links-remote, analytics-remote]
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::012345678901:role/github-actions-eks
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          MFE_NAME: ${{ matrix.mfe }}
        run: |
          IMAGE="$REGISTRY/url-shortener/frontend-${MFE_NAME}"
          docker build \
            -f url-shortener-ui/Dockerfile.mfe \
            --build-arg MFE_NAME=${MFE_NAME} \
            -t "$IMAGE:$IMAGE_TAG" \
            -t "$IMAGE:latest" \
            url-shortener-ui
          docker push "$IMAGE:$IMAGE_TAG"
          docker push "$IMAGE:latest"
